# Generated by Django 5.2.8 on 2026-03-25 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr22', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('sku', models.CharField(help_text='Código único del repuesto', max_length=50, unique=True)),
                ('precio_costo', models.DecimalField(decimal_places=2, help_text='Costo para el taller', max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio al cliente', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible')),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
                ('marca', models.CharField(help_text='Fabricante del repuesto', max_length=100)),
                ('garantia_meses', models.PositiveIntegerField(default=12, help_text='Meses de garantía')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('descontinuado', 'Descontinuado')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='cdr22.categoria')),
            ],
            options={
                'db_table': 'productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
