# Generated by Django 5.2.8 on 2026-05-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr22', '0004_orden_impuesto_orden_subtotal_alter_orden_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Impuesto (IVA, etc.)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orden',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orden',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orden',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, help_text='Costo para el taller', max_digits=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, help_text='Precio al cliente', max_digits=15),
        ),
    ]
