# Generated by Django 5.2.8 on 2026-06-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr22', '0006_compra_proveedor_compraitem_compra_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('credito', 'Crédito'), ('otro', 'Otro')], max_length=100, null=True),
        ),
    ]
