# Generated by Django 5.2.8 on 2026-06-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr22', '0007_alter_compra_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='anulada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_espera', 'En espera'), ('completada', 'Completada'), ('anulada', 'Anulada')], default='borrador', max_length=20),
        ),
    ]
