# Generated by Django 5.2.8 on 2026-06-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr22', '0008_compra_anulada_en_compra_motivo_anulacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Las Motos', max_length=150)),
                ('prefijo_factura', models.CharField(default='FAC', max_length=10)),
                ('siguiente_numero_factura', models.PositiveIntegerField(default=1)),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('moneda', models.CharField(default='COP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
    ]
