# Generated by Django 5.2.8 on 2026-06-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr22', '0009_configuracionsistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='moneda',
            field=models.CharField(choices=[('COP', 'COP - Peso colombiano')], default='COP', max_length=10),
        ),
    ]
