# Generated by Django 5.2.8 on 2026-06-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr22', '0010_alter_configuracionsistema_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresa/logos/'),
        ),
    ]
