# Generated by Django 5.2.8 on 2026-06-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr22', '0011_configuracionsistema_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='ciudad_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='direccion_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='pais_empresa',
            field=models.CharField(blank=True, default='Colombia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='telefono_empresa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
