ROLE_ADMINISTRADOR = 'Administrador'
ROLE_VENDEDOR = 'Vendedor'
ROLE_GERENTE = 'Gerente'

ROLE_NAMES = [
    ROLE_ADMINISTRADOR,
    ROLE_VENDEDOR,
    ROLE_GERENTE,
]

USER_MANAGER_ROLES = [
    ROLE_ADMINISTRADOR,
    ROLE_GERENTE,
]
